services:
  backend:
    build: ./
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    depends_on:
      - mysql
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]
    environment:
      - NODE_ENV=development
    networks:
      - cloud-network

  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cloud-network

volumes:
  mysql_data:
  
networks:
  cloud-network: