services:
  backend:
    build: ./
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306", "--", "npm", "start"]

  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  